title: Chris Gonzales
logo: assets/img/M2.0p.png
description: I am recent undergraduate Business Analytics degree from Cal State Fullerton, I honed my skills as Vice President of Business and Data Analytics, using insights to optimize operations. My leadership experience in the American Marketing Association strengthened my ability to mentor and drive professional growth. Outside of work, I stay motivated through basketball, volleyball, and photography, which keep me balanced and inspired.
show_downloads: true
theme: jekyll-theme-minimal 
